name: Test

on: push

jobs:
  ubuntu-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: build-tests
      run: |
        cmake -DPARALLELUTIL_BUILD_TESTS=ON .
        make
    - name: ctest
      run: ctest

  macos-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build-tests
      run: |
        cmake -DPARALLELUTIL_BUILD_TESTS=ON .
        make
    - name: ctest
      run: ctest
